### ISSUE TITLE
Databricks: Error Creating Cluster 

### ISSUE THREAD

**Issue by adamwongnz** [NZMSA/2019-Phase-1#2]
When trying to create a cluster using the settings provided in the guide, I'm receiving this error.
Any ideas on how to fix it? I've tried deleting the resource groups and starting from scratch but I'm still receiving it. 
![image](https://user-images.githubusercontent.com/38397099/56262255-0f08ba00-6132-11e9-812c-db469492df54.png)

**Comment by MSP-Khoda** [comment]
> When trying to create a cluster using the settings provided in the guide, I'm receiving this error.
> Any ideas on how to fix it? I've tried deleting the resource groups and starting from scratch but I'm still receiving it.
> ![image](https://user-images.githubusercontent.com/38397099/56262255-0f08ba00-6132-11e9-812c-db469492df54.png)

Hi @adamwongnz
This is because free trial subscriptions on Azure are limited to a total of 4 cores for VMs. When creating clusters, as there is a Worker node and Driver node, on the lowest available configuration this will end in a total of 8 cores exceeding the 4 core limit. We are currently in the process of migrating to use Azure Notebooks instead of Azure Databricks due to this. We will let you know once the documentation reflects this.
Thanks Khoda

**Comment by MSP-Khoda** [comment]
Hi @adamwongnz
Documentation has been updated to use Azure Notebooks. You should be able to go through the tutorial now. 
Thanks Khoda
